version: "3.2"
services:
    envoygateway:
      build: Envoy/
      ports:
         - "9901:9901"
         - "10000:10000"
      volumes:
         - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
    authenticationapi:
        image: authenticationapi
        build: 
          context: .
          dockerfile: Api.Shopping.Authentication/Dockerfile
        ports:
          - "8080:80"
          - "8081:443"
        environment:
          - ASPNETCORE_URLS=https://+:443;http://+:80
          - ASPNETCORE_HTTPS_PORT=8081
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Api.Shopping.Authentication.pfx
        volumes:
          - ~/.aspnet/https:/https:ro
          # - ${APPDATA}/microsoft/UserSecrets/:/root/.microsoft/usersecrets:rw
          # - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https:ro
    paymentsapi:
          image: paymentsapi
          build:
            context: .
            dockerfile: Api.Shopping.Payment/Dockerfile
          ports:
            - "8082:80"
            - "8083:443"
          environment:
            - ASPNETCORE_URLS=https://+;http://+
            - ASPNETCORE_HTTPS_PORT=8083
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Api.Shopping.Payment.pfx
          volumes:
            - ~/.aspnet/https:/https:ro
    catalogueapi:
          image: catalogueapi
          build: 
            context: .
            dockerfile: Api.Shopping.Catalogue/Dockerfile
          ports:
            - "10080:80"
            - "10081:443"
          environment:
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=10081
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Api.Shopping.Catalogue.pfx
          volumes:
            - ~/.aspnet/https:/https:ro
            - /wwwroot/


